config/routes.rb
Rails.application.routes.draw do

  root 'joins#new'

  devise_for :admins
  resources :joins
  resources :blogs
  devise_for :users

  #Blog
  get 'blogs/new'

  get 'blogs/show'

  get 'blogs/edit'

  get 'blogs/destroy'

  #Join
  get 'joins/index'

  get 'joins/show'

  #Home
  get 'home/contactus'

  get 'home/home'

  get 'home/howitworks'

  get 'home/list'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/join.rb
class Join < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog
    else
      render 'new'
    end
  end

  def show

  end

  def edit

  end

  def update

    if @blog.update(blog_params)
      redirect_to @blog
    else
      render 'edit'
    end

  end

  def destroy
    @blog.destroy
    redirect_to root_path
  end

  def index
    @blogs = Blog.all.order(created_at: :desc)
  end

  private

    def find_post
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :body, :image)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def list
  end

  def about
  end

  def admin
    current_user.update_attribute :admin, true
  end
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController

  def new
    @join = Join.new
  end

  def create
    @join = Join.new(post_params)

    if @join.save
      redirect_to @join
    else
      render 'new'
    end
  end

  def show

  end

  def destroy
    @join = Join.find(params[:id])
    @join.destroy
    redirect_to root_path
  end


  private

  def post_params
    params.require(:join).permit(:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/views/blogs/_blogsform.html.erb
<% if current_user.try(:email) == "sbhenrichs@gmail.com" || "camblackwell2@gmail.com"%>
<br>
<div class="form-horizontal">
  <fieldset>
    <%= form_for @blog do |f| %>
    <div class="form-group">
      <label class="col-lg-2">Image</label>
      <div class="col-lg-10">
        <%= f.file_field :image, id: "choose-file" %>
      </div>
    </div>
    <div class="form-group">
      <label for="" class="col-lg-2">Title</label>
      <div class="col-lg-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="" class="col-lg-2">Body</label>
      <div class="col-lg-10">
        <%= f.text_area :body, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-2"></div>
      <div class="col-lg-10">
        <%= f.submit "Update/Create Post", class: "btn btn-primary" %>
      </div>
    </div>
    <% end %>
    <% else %>
    <div><h3>Congrats on finding this page! Unfourtunately, you're not an admin, so you can't make a new blog post, but you can still <a href="/blogs">read them.</a><h3></div>
  <% end %>

app/views/blogs/destroy.html.erb
<h1>Blogs#destroy</h1>
<p>Find me in app/views/blogs/destroy.html.erb</p>

app/views/blogs/edit.html.erb
<html>
  <head>

  </head>
  <body>
    <h3>Update Blog</h3>
    <%= render 'blogsform' %>
  </body>
</html>

app/views/blogs/index.html.erb
<html>
  <head>

  </head>
  <body>

    <% @blogs.each do |blog| %>
    <div class="blog col-lg-12">
    <h3 class="blog-title"><%= link_to blog.title, blog, class: "blog-title blog-links" %></h3>
    <h5 class="blog-body"><%= truncate(blog.body, :length => 100) %></h5>
    <% if current_user.try(:email) == "sbhenrichs@gmail.com" || "camblackwell2@gmail.com" %>
      <%= link_to "Delete Blog", blog_path(blog), method: :delete, data: { confirm: "Are you sure? Don't screw up." } %>
    <% end %>
    </div>
    <% end %>

  </body>
</html>

app/views/blogs/new.html.erb
<html>
  <head>

  </head>
  <body>

    <br>
    <h3>New Blog</h3>
      <%= render 'blogsform' %>
        </fieldset>
      </div>
  </body>
</html>

app/views/blogs/show.html.erb
<html>
  <head>

  </head>
  <body>
    <div>
      <div class="col-lg-2"></div>
      <div class="blog-show col-lg-8">
      <h2><%= @blog.title %></h2>
      <h5 class="blog-body"><%= @blog.body %></h5>
      <% if current_user.try(:email) == "sbhenrichs@gmail.com" || "camblackwell2@gmail.com" %>
        <%= link_to "Update Post", edit_blog_path(@blog) %>
      <% end %>
    </div>
    </div>
  </body>
</html>

app/views/home/about.html.erb
<html>
  <head>
    <title>Let's make shopping a little lucky.</title>
  </head>
  <body>

  </body>

  <div class="jumbotron">
    <h1>Welcome to rewardsApp. We're glad you're here.</h1>
    <p>Want to sign up? Click here. If you want to get started, keep scrolling.</p>
  </div>
</html>

app/views/home/admin.html.erb
<html>
  <head>

  </head>
  <body>
    
  </body>
</html>

app/views/home/contactus.html.erb
<html>
  <head>

  </head>
  <body>
    <h3>You want to talk to us? We're flattered.</h3>
    <h5>We hate contact forms, so we decided not to make one for our website. Instead, you can email us at info@avacadorewards.com. When you do, we can answer any of your questions, like:</h5>
    <br>
    <ul>
      <li><h5>How to sign up</h5></li>
      <li><h5>How to join the rewards</h5></li>
      <li><h5>Our favorite color (green)</h5></li>
      <li><h5>And how we made such a cool site. We'd be happen to fill you in.</h5></li>
    </ul>
  </body>
</html>

app/views/home/home.html.erb
<html>
  <head>

  </head>
  <body>
  </body>
</html>

app/views/home/howitworks.html.erb
<html>
  <head>
    <title>Let's make shopping a little lucky.</title>
  </head>
  <body>

  </body>

  <div class="jumbotron">
    <h1>Welcome to rewardsApp. We're glad you're here.</h1>
    <h5>Want to sign up? Click here. If you want to get started, keep scrolling.</h5>
  </div>
</html>

app/views/home/index.html.erb
<html>
  <head>

  </head>
  <body>
    
  </body>
</html>

app/views/home/list.html.erb
<html>
  <head>

  </head>
  <body>
    <% if current_user.try(:email) == "sbhenrichs@gmail.com" || "camblackwell2@gmail.com" %>
    <h3 class="text-success">Users:</h3>
    <table class="table table-striped table-hover">
      <tr>
        <td>
          <% @user = User.all %>
          <% @user.each do |user| %>
            <%= user.email %> <br>
          <% end %>
        </td>
      </tr>
    </table>
    <% end %>
  </body>
</html>

app/views/joins/new.html.erb
<html>
  <head>

  </head>
  <body>
    <% if Join.exists?(email: current_user.try(:email)) %>
      <h3>You're already signed up for this month! Thanks!</h3>
    <% else %>
      <% if user_signed_in? %>
      <div>
        <h3 class="center">Want to join? Just click the button below.</h3>
      </div>
      <%= form_for @join do |f| %>
        <%= f.email_field :email, value: current_user.email, class: "form-control input-lg", type: "hidden" %> <br>
        <%= f.submit "Join This Month's Rewards", class: "btn btn-primary", id: "join" %>
      <% end %>
      <% else %>
        <h3>Sorry, you're not currently signed in, so you can't sign up for our rewards. You can sign in <a href="/users/sign_in">here.</a></h3>
    <% end %>
    <% end %>
  </body>
</html>

app/views/joins/show.html.erb
<html>
  <head>

  </head>
  <body>
    <% if current_user.try(:email) == "sbhenrichs@gmail.com" || "camblackwell2@gmail.com"%>
    <h3 class="text-success">Signed-Up Users:</h3>
    <table class="table table-striped table-hover">
      <tr>
        <td>
          <% @join = Join.all %>
          <% @join.each do |join| %>
            <%= join.email %> <%= link_to "Delete Joined User", join_path(join), method: :delete, data: { confirm: "Are you sure? Don't screw up." } %><br>
          <% end %>
        </td>
      </tr>
    </table>
    <% else %>
    <h3>Thanks for signing up! You'll get an email at the end of the month letting you know if you won.</h3>
    <% end %>
  </body>
</html>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
  <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/joins/new">
          Yeti Rewards
          <% if current_user.try(:email) == "sbhenrichs@gmail.com" || "camblackwell2@gmail.com" %>
          <em>Admin</em>
          <% end %>
        </a>
      </div>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav">
    <li><a href="/joins/new">Home</a></li>
    <li><a href="/home/howitworks">How It Works</a></li>
    <li><a href="/blogs">Blog</a></li>
    <li><a href="/home/contactus">Contact Us</a></li>
    <% if current_user.try(:email) == "sbhenrichs@gmail.com" || "camblackwell2@gmail.com" %>
    <li><a href="/joins/show">Signed-Up Users</a></li>
    <li><a href="/home/list">Users</a></li>
    <li><a href="/blogs/new">Create Blog</a></li>
    <% end %>
  </ul>
  <ul class="nav navbar-nav navbar-right .visible-lg-*">
   <% if user_signed_in? %>
     <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
     <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
   <% else %>
     <li><%= link_to "Sign Up", new_user_registration_path %></li>
     <li><%= link_to "Sign In", new_user_session_path %></li>
   <% end %>
 </ul>
</div>
</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Yeti Rewards</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>


<div class="container">
  <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
<%= yield %>
</div>
</body>
</html>